@php
    $setting          = App\Models\Utility::settings();
    $plan             = App\Models\Utility::getChatGPTSettings();
    $company_settings = \App\Models\Utility::settings();
@endphp

{{ Form::open(['url' => 'leave', 'method' => 'post', 'class' => 'needs-validation', 'novalidate']) }}
<div class="modal-body">

    @if ($plan->enable_chatgpt == 'on')
        <div class="card-footer text-end mb-2">
            <a href="javascript:void(0)" class="btn btn-sm btn-primary" data-size="medium"
                data-ajax-popup-over="true" data-url="{{ route('generate', ['leave']) }}"
                data-bs-toggle="tooltip" data-bs-placement="top" title="{{ __('Generate') }}"
                data-title="{{ __('Generate Content With AI') }}">
                <i class="fas fa-robot"></i>{{ __(' Generate With AI') }}
            </a>
        </div>
    @endif

    {{-- Employee --}}
    @if (\Auth::user()->type != 'employee')
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {{ Form::label('employee_id', __('Employee'), ['class' => 'col-form-label']) }}<x-required></x-required>
                    {{ Form::select('employee_id', $employees, null, ['class' => 'form-control', 'id' => 'employee_id', 'required' => 'required', 'placeholder' => __('Select Employee')]) }}
                    <div class="text-xs mt-1">
                        {{ __('Create employee.') }}
                        <a href="{{ route('employee.index') }}"><b>{{ __('Click here') }}</b></a>
                    </div>
                </div>
            </div>
        </div>
    @else
        {!! Form::hidden('employee_id', !empty($employees) ? $employees->id : 0, ['id' => 'employee_id']) !!}
    @endif

    {{-- Leave Type --}}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('leave_type_id', __('Leave Type'), ['class' => 'col-form-label']) }}<x-required></x-required>
                <select name="leave_type_id" id="leave_type_id" class="form-control select" required>
                    @if (\Auth::user()->type != 'employee')
                        <option value="">{{ __('Select Employee First') }}</option>
                    @else
                        <option value="">{{ __('Select Leave Type') }}</option>
                        @foreach ($leavetypes as $ltype)
                            <option value="{{ $ltype->id }}"
                                data-is-paid="{{ $ltype->is_paid ? 1 : 0 }}"
                                data-days="{{ $ltype->days }}">
                                {{ $ltype->title }} ({{ $ltype->days }} {{ __('days') }})
                            </option>
                        @endforeach
                    @endif
                </select>
                @can('Create Leave Type')
                    <div class="text-xs mt-1">
                        {{ __('Create leave type.') }}
                        <a href="{{ route('leavetype.index') }}"><b>{{ __('Click here') }}</b></a>
                    </div>
                @endcan
                {{-- Info bar shown when a leave type is selected --}}
                <div id="leave_type_info" class="mt-2" style="display:none;">
                    <span id="leave_type_pay_badge"></span>
                    <span id="leave_type_remaining" class="ms-2 text-muted small"></span>
                </div>
            </div>
    </div>

    {{-- Sandwich Leave Notice (Shown ONLY when leave spans across weekend/holiday) --}}
    <div id="sandwich_leave_notice" class="alert alert-warning border-warning align-items-center mb-3" style="display:none;">
        <div class="d-flex align-items-center">
            <i class="ti ti-alert-triangle fs-4 me-2 text-warning"></i>
            <div>
                <strong>{{ __('Sandwich Leave Notice') }}:</strong>
                <span>{{ __('This leave application includes intervening Day Off / Weekend dates. Sandwich Leave rules apply.') }}</span>
            </div>
        </div>
    </div>

    {{-- Date range --}}
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                {{ Form::label('start_date', __('Start Date'), ['class' => 'col-form-label']) }}<x-required></x-required>
                {{ Form::date('start_date', null, ['class' => 'form-control', 'id' => 'start_date', 'required' => 'required', 'autocomplete' => 'off']) }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ Form::label('end_date', __('End Date'), ['class' => 'col-form-label']) }}<x-required></x-required>
                {{ Form::date('end_date', null, ['class' => 'form-control current_date', 'id' => 'end_date', 'required' => 'required', 'autocomplete' => 'off']) }}
            </div>
        </div>
    </div>

    {{-- ── Per-day breakdown table (generated by JS) ──────────────────────── --}}
    <div class="day-breakdown-wrapper mb-2" style="display:none;">
        <label class="col-form-label fw-bold">{{ __('Day-wise Leave Details') }}</label>
        <div class="table-responsive">
            <table class="table table-sm table-bordered align-middle">
                <thead class="table-light">
                    <tr>
                        <th>{{ __('Date') }}</th>
                        <th>{{ __('Day') }}</th>
                        <th>{{ __('Duration') }}</th>
                        <th>{{ __('Period') }}<small class="text-muted d-block">{{ __('(if half day)') }}</small></th>
                        <th>{{ __('Status') }}</th>
                        @if (\Auth::user()->type != 'employee')
                            <th>{{ __('Sandwich Rule') }}</th>
                        @endif
                    </tr>
                </thead>
                <tbody class="day-breakdown-body"></tbody>
            </table>
        </div>
        <div class="mt-1 text-muted small day-summary"></div>
    </div>

    {{-- Leave Note --}}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('leave_reason', __('Leave Note'), ['class' => 'col-form-label']) }}<x-required></x-required>
                {{ Form::textarea('leave_reason', null, ['class' => 'form-control', 'required' => 'required', 'placeholder' => __('Leave Reason'), 'rows' => '3']) }}
            </div>
        </div>
    </div>

    {{-- Remark --}}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('remark', __('Remark'), ['class' => 'col-form-label']) }}<x-required></x-required>
                @if ($plan->enable_chatgpt == 'on')
                    <a href="javascript:void(0)" data-size="md" class="btn btn-primary btn-icon btn-sm"
                        data-ajax-popup-over="true" id="grammarCheck"
                        data-url="{{ route('grammar', ['grammar']) }}" data-bs-placement="top"
                        data-title="{{ __('Grammar check with AI') }}">
                        <i class="ti ti-rotate"></i> <span>{{ __('Grammar check with AI') }}</span>
                    </a>
                @endif
                {{ Form::textarea('remark', null, ['class' => 'form-control grammer_textarea', 'required' => 'required', 'placeholder' => __('Leave Remark'), 'rows' => '3']) }}
            </div>
        </div>
    </div>

    @if (isset($setting['is_enabled']) && $setting['is_enabled'] == 'on')
        <div class="form-group col-md-6">
            {{ Form::label('synchronize_type', __('Synchroniz in Google Calendar ?'), ['class' => 'form-label']) }}
            <div class="form-switch">
                <input type="checkbox" class="form-check-input mt-2" name="synchronize_type"
                    id="switch-shadow" value="google_calender">
                <label class="form-check-label" for="switch-shadow"></label>
            </div>
        </div>
    @endif

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
    <input type="submit" value="{{ __('Create') }}" class="btn btn-primary">
</div>
{{ Form::close() }}

<script>
(function () {
    'use strict';

    // Scope everything to this form — avoids conflicts with other modal forms
    var $form = $('form[action="{{ url('leave') }}"]').last();
    if (!$form.length) return;

    var isEmployee    = {{ \Auth::user()->type === 'employee' ? 'true' : 'false' }};
    var phpDateFormat = '{{ \App\Models\Utility::settings()['site_date_format'] ?? 'd-m-Y' }}';
    var dayNames      = ['{{ __("Sun") }}','{{ __("Mon") }}','{{ __("Tue") }}','{{ __("Wed") }}','{{ __("Thu") }}','{{ __("Fri") }}','{{ __("Sat") }}'];
    var leaveTypeData = {};

    // ── Init ───────────────────────────────────────────────────────────────
    var eid = $form.find('#employee_id').val();
    if (eid) loadLeaveTypesAjax(eid, true);

    // ── Events scoped to this form ─────────────────────────────────────────
    $form.on('change', '#start_date, #end_date', buildBreakdown);

    $form.on('change', '#leave_type_id', function () {
        updateLeaveTypeInfo($(this).val());
        buildBreakdown();
    });

    $form.on('change', '#employee_id', function () {
        if (isEmployee) return;
        var emp_id = $(this).val();
        if (!emp_id) return;
        $form.find('#leave_type_id').empty().append('<option value="">{{ __("Loading…") }}</option>');
        $form.find('.day-breakdown-wrapper').hide();
        loadLeaveTypesAjax(emp_id, false);
    });

    $form.on('change', '.dur-radio', function () {
        var isHalf = $(this).val() === 'half_day';
        var $cell  = $(this).closest('tr').find('.period-cell');
        $cell.find('.period-dash').toggle(!isHalf);
        $cell.find('.period-select').toggle(isHalf);
        updateSummary();
    });

    $form.on('change', '.stat-radio', updateSummary);

    // ── AJAX: load leave types with balance ────────────────────────────────
    function loadLeaveTypesAjax(employeeId, isInitial) {
        $.ajax({
            url: '{{ route('leave.jsoncount') }}',
            type: 'POST',
            data: { employee_id: employeeId, _token: '{{ csrf_token() }}' },
            success: function (data) {
                leaveTypeData = {};
                var $sel   = $form.find('#leave_type_id');
                var oldval = $sel.val();
                $sel.empty().append('<option value="">{{ __("Select Leave Type") }}</option>');

                $.each(data, function (k, v) {
                    leaveTypeData[v.id] = {
                        is_paid:     v.is_paid ? 1 : 0,
                        remaining:   parseFloat(v.remaining),
                        days:        parseFloat(v.days),
                        total_leave: parseFloat(v.total_leave),
                    };
                    var label    = v.title + ' (' + v.total_leave + '/' + v.days
                                 + ' {{ __("used") }}, {{ __("Remaining") }}: ' + v.remaining + ')';
                    var disabled = (v.remaining <= 0 && v.is_paid) ? ' disabled' : '';
                    $sel.append('<option value="' + v.id + '"' + disabled
                        + ' data-is-paid="' + (v.is_paid ? 1 : 0) + '"'
                        + ' data-remaining="' + v.remaining + '">' + label + '</option>');
                });

                // Restore previous selection if still available
                if (oldval && $sel.find('option[value="' + oldval + '"]').length) {
                    $sel.val(oldval);
                }

                updateLeaveTypeInfo($sel.val());
                buildBreakdown();
            },
            error: function () {
                $form.find('#leave_type_id').empty()
                    .append('<option value="">{{ __("Select Leave Type") }}</option>');
            }
        });
    }

    // ── Helpers ────────────────────────────────────────────────────────────
    function formatDate(d) {
        var yyyy = d.getFullYear(),
            mm   = String(d.getMonth() + 1).padStart(2, '0'),
            dd   = String(d.getDate()).padStart(2, '0');
        return phpDateFormat
            .replace('Y', yyyy).replace('y', String(yyyy).slice(-2))
            .replace('m', mm).replace('n', String(d.getMonth() + 1))
            .replace('d', dd).replace('j', String(d.getDate()));
    }

    function updateLeaveTypeInfo(id) {
        var $info = $form.find('#leave_type_info');
        if (!id) { $info.hide(); return; }
        var ltd       = leaveTypeData[id];
        var opt       = $form.find('#leave_type_id option[value="' + id + '"]');
        var isPaid    = ltd ? ltd.is_paid   : parseInt(opt.data('is-paid') || 1);
        var remaining = ltd ? ltd.remaining : parseFloat(opt.data('remaining') || opt.data('days') || 0);
        var payBadge  = isPaid
            ? '<span class="badge bg-success"><i class="ti ti-circle-check me-1"></i>{{ __("Paid Leave") }}</span>'
            : '<span class="badge bg-danger"><i class="ti ti-circle-x me-1"></i>{{ __("Unpaid Leave") }}</span>';
        var remClass  = remaining > 0 ? 'text-success' : 'text-danger';
        $form.find('#leave_type_pay_badge').html(payBadge);
        $form.find('#leave_type_remaining').html(
            '<span class="' + remClass + ' fw-semibold">{{ __("Remaining") }}: ' + remaining + ' {{ __("day(s)") }}</span>'
        );
        $info.show();
    }

    function buildBreakdown() {
        var sd = $form.find('#start_date').val();
        var ed = $form.find('#end_date').val();
        var $wrapper = $form.find('.day-breakdown-wrapper');

        if (!sd || !ed) { $wrapper.hide(); return; }
        var start = new Date(sd), end = new Date(ed);
        if (isNaN(start) || isNaN(end) || end < start) { $wrapper.hide(); return; }

        var ltId      = $form.find('#leave_type_id').val();
        var ltd       = ltId ? leaveTypeData[ltId] : null;
        var opt       = ltId ? $form.find('#leave_type_id option[value="' + ltId + '"]') : null;
        var isPaid    = ltd ? ltd.is_paid   : (opt ? parseInt(opt.data('is-paid') || 1) : 1);
        var remaining = ltd ? ltd.remaining : 9999;

        var diffDays   = Math.round((end - start) / 86400000) + 1;
        var $tbody     = $form.find('.day-breakdown-body');
        var paidBudget = remaining;
        $tbody.empty();

        for (var i = 0; i < diffDays; i++) {
            var cur  = new Date(start);
            cur.setDate(start.getDate() + i);
            var yyyy    = cur.getFullYear();
            var m       = String(cur.getMonth() + 1).padStart(2, '0');
            var d       = String(cur.getDate()).padStart(2, '0');
            var dateStr = yyyy + '-' + m + '-' + d;
            var status, locked;
            if (!isPaid) {
                status = 'unpaid'; locked = isEmployee;
            } else if (paidBudget <= 0) {
                status = 'unpaid'; locked = isEmployee;
            } else {
                status = 'paid'; locked = false; paidBudget -= 1.0;
            }
            $tbody.append(buildRow(dateStr, formatDate(cur), dayNames[cur.getDay()], 'full_day', 'morning', status, locked));
        }

        checkSandwichCondition(start, end);
        updateSummary();
        $wrapper.show();
    }

    function checkSandwichCondition(start, end) {
        var diffDays = Math.round((end - start) / 86400000) + 1;
        if (diffDays <= 1) {
            $form.find('#sandwich_leave_notice').hide();
            return;
        }

        var hasWeekendInside = false;

        for (var i = 0; i < diffDays; i++) {
            var cur = new Date(start);
            cur.setDate(start.getDate() + i);
            var dow = cur.getDay(); // 0 = Sun, 6 = Sat

            if (dow === 0 || dow === 6) {
                hasWeekendInside = true;
            }
        }

        if (hasWeekendInside && diffDays > 1) {
            $form.find('#sandwich_leave_notice').fadeIn();
        } else {
            $form.find('#sandwich_leave_notice').hide();
        }
    }

    function buildRow(dateStr, dateDisp, dayName, duration, period, status, locked) {
        var uid        = dateStr.replace(/-/g, '_');
        var dis        = locked ? ' disabled' : '';
        var isHalf     = duration === 'half_day';
        var lockBadge  = locked
            ? '<span class="badge bg-secondary ms-1"><i class="ti ti-lock"></i></span>' : '';
        var hiddenStat = locked
            ? '<input type="hidden" name="day_status[' + dateStr + ']" value="' + status + '">' : '';
        var statName   = locked ? '_day_status_display[' + dateStr + ']' : 'day_status[' + dateStr + ']';

        var isNotEmp = {{ \Auth::user()->type !== 'employee' ? 'true' : 'false' }};
        var sRuleCell = '';
        if (isNotEmp) {
            var sRuleOptions = '<option value="">{{ __("None") }}</option>';
            @if (isset($sandwichRules) && count($sandwichRules) > 0)
                @foreach ($sandwichRules as $srule)
                    sRuleOptions += '<option value="{{ $srule->id }}">{{ $srule->name }} ({{ number_format($srule->deduction_rate, 2) }}{{ $srule->rate_type == "percentage" ? "%" : "x" }})</option>';
                @endforeach
            @endif
            sRuleCell = '<td><select name="sandwich_leave_rule_id[' + dateStr + ']" class="form-select form-select-sm">' + sRuleOptions + '</select></td>';
        }

        return '<tr data-date="' + dateStr + '">'
            + '<td><small>' + dateDisp + '</small></td>'
            + '<td><small>' + dayName + '</small></td>'
            + '<td>'
            +   '<div class="form-check form-check-inline"><input class="form-check-input dur-radio" type="radio" name="day_duration[' + dateStr + ']" id="full_' + uid + '" value="full_day"' + (!isHalf ? ' checked' : '') + '><label class="form-check-label" for="full_' + uid + '">{{ __("Full") }}</label></div>'
            +   '<div class="form-check form-check-inline"><input class="form-check-input dur-radio" type="radio" name="day_duration[' + dateStr + ']" id="half_' + uid + '" value="half_day"' + (isHalf ? ' checked' : '') + '><label class="form-check-label" for="half_' + uid + '">{{ __("Half") }}</label></div>'
            + '</td>'
            + '<td class="period-cell">'
            +   '<span class="period-dash"' + (isHalf ? ' style="display:none;"' : '') + '>-</span>'
            +   '<select name="half_day_period_day[' + dateStr + ']" class="form-control form-control-sm period-select"' + dis + (!isHalf ? ' style="display:none;"' : '') + '>'
            +     '<option value="morning"' + (period === 'morning' ? ' selected' : '') + '>{{ __("Morning") }}</option>'
            +     '<option value="afternoon"' + (period === 'afternoon' ? ' selected' : '') + '>{{ __("Afternoon") }}</option>'
            +   '</select>'
            + '</td>'
            + '<td>'
            +   hiddenStat
            +   '<div class="form-check form-check-inline"><input class="form-check-input stat-radio" type="radio" name="' + statName + '" id="paid_' + uid + '" value="paid"' + (status === 'paid' ? ' checked' : '') + dis + '><label class="form-check-label text-success" for="paid_' + uid + '">{{ __("Paid") }}</label></div>'
            +   '<div class="form-check form-check-inline"><input class="form-check-input stat-radio" type="radio" name="' + statName + '" id="unpaid_' + uid + '" value="unpaid"' + (status === 'unpaid' ? ' checked' : '') + dis + '><label class="form-check-label text-danger" for="unpaid_' + uid + '">{{ __("Unpaid") }}</label></div>'
            +   lockBadge
            + '</td>' + sRuleCell + '</tr>';
    }

    function updateSummary() {
        var total = 0, paid = 0, unpaid = 0;
        $form.find('.day-breakdown-body tr').each(function () {
            var dur  = $(this).find('.dur-radio:checked').val() || 'full_day';
            var days = dur === 'half_day' ? 0.5 : 1.0;
            var hidden = $(this).find('input[type="hidden"][name^="day_status"]');
            var stat = hidden.length ? hidden.val()
                     : ($(this).find('.stat-radio:checked').val() || 'paid');
            total += days;
            if (stat === 'paid') paid += days; else unpaid += days;
        });
        $form.find('.day-summary').html(
            '<strong>{{ __("Total") }}:</strong> ' + total + ' &nbsp;|&nbsp; '
            + '<span class="text-success"><strong>{{ __("Paid") }}:</strong> ' + paid + '</span> &nbsp;|&nbsp; '
            + '<span class="text-danger"><strong>{{ __("Unpaid") }}:</strong> ' + unpaid + '</span>'
        );
    }

}());
</script>
