@php
    $setting          = App\Models\Utility::settings();
    $plan             = App\Models\Utility::getChatGPTSettings();
    $company_settings = \App\Models\Utility::settings();
@endphp

{{ Form::open(['url' => 'leave', 'method' => 'post', 'class' => 'needs-validation', 'novalidate']) }}
<div class="modal-body">

    @if ($plan->enable_chatgpt == 'on')
        <div class="card-footer text-end mb-2">
            <a href="javascript:void(0)" class="btn btn-sm btn-primary" data-size="medium"
                data-ajax-popup-over="true" data-url="{{ route('generate', ['leave']) }}"
                data-bs-toggle="tooltip" data-bs-placement="top" title="{{ __('Generate') }}"
                data-title="{{ __('Generate Content With AI') }}">
                <i class="fas fa-robot"></i>{{ __(' Generate With AI') }}
            </a>
        </div>
    @endif

    {{-- Employee --}}
    @if (\Auth::user()->type != 'employee')
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {{ Form::label('employee_id', __('Employee'), ['class' => 'col-form-label']) }}<x-required></x-required>
                    {{ Form::select('employee_id', $employees, null, ['class' => 'form-control', 'id' => 'employee_id', 'required' => 'required', 'placeholder' => __('Select Employee')]) }}
                    <div class="text-xs mt-1">
                        {{ __('Create employee.') }}
                        <a href="{{ route('employee.index') }}"><b>{{ __('Click here') }}</b></a>
                    </div>
                </div>
            </div>
        </div>
    @else
        {!! Form::hidden('employee_id', !empty($employees) ? $employees->id : 0, ['id' => 'employee_id']) !!}
    @endif

    {{-- Leave Type --}}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('leave_type_id', __('Leave Type'), ['class' => 'col-form-label']) }}<x-required></x-required>
                <select name="leave_type_id" id="leave_type_id" class="form-control select" required>
                    @if (\Auth::user()->type != 'employee')
                        <option value="">{{ __('Select Employee First') }}</option>
                    @else
                        <option value="">{{ __('Select Leave Type') }}</option>
                        @foreach ($leavetypes as $ltype)
                            <option value="{{ $ltype->id }}"
                                data-is-paid="{{ $ltype->is_paid ? 1 : 0 }}"
                                data-days="{{ $ltype->days }}">
                                {{ $ltype->title }} ({{ $ltype->days }} {{ __('days') }})
                            </option>
                        @endforeach
                    @endif
                </select>
                @can('Create Leave Type')
                    <div class="text-xs mt-1">
                        {{ __('Create leave type.') }}
                        <a href="{{ route('leavetype.index') }}"><b>{{ __('Click here') }}</b></a>
                    </div>
                @endcan
                {{-- Info bar shown when a leave type is selected --}}
                <div id="leave_type_info" class="mt-2" style="display:none;">
                    <span id="leave_type_pay_badge"></span>
                    <span id="leave_type_remaining" class="ms-2 text-muted small"></span>
                </div>
            </div>
        </div>
    </div>

    {{-- Date range --}}
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                {{ Form::label('start_date', __('Start Date'), ['class' => 'col-form-label']) }}<x-required></x-required>
                {{ Form::date('start_date', null, ['class' => 'form-control', 'id' => 'start_date', 'required' => 'required', 'autocomplete' => 'off']) }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                {{ Form::label('end_date', __('End Date'), ['class' => 'col-form-label']) }}<x-required></x-required>
                {{ Form::date('end_date', null, ['class' => 'form-control current_date', 'id' => 'end_date', 'required' => 'required', 'autocomplete' => 'off']) }}
            </div>
        </div>
    </div>

    {{-- ── Per-day breakdown table (generated by JS) ──────────────────────── --}}
    {{--
        Columns per day:
          • Date / Day name
          • Duration  : Full Day / Half Day  (radio)
          • Period    : Morning / Afternoon  (shown only when Half Day selected for that row)
          • Status    : Paid / Unpaid        (radio)
    --}}
    <div id="day_breakdown_wrapper" style="display:none;" class="mb-2">
        <label class="col-form-label fw-bold">{{ __('Day-wise Leave Details') }}</label>
        <div class="table-responsive">
            <table class="table table-sm table-bordered align-middle" id="day_breakdown_table">
                <thead class="table-light">
                    <tr>
                        <th>{{ __('Date') }}</th>
                        <th>{{ __('Day') }}</th>
                        <th>{{ __('Duration') }}</th>
                        <th>{{ __('Period') }}<small class="text-muted d-block">{{ __('(if half day)') }}</small></th>
                        <th>{{ __('Status') }}</th>
                    </tr>
                </thead>
                <tbody id="day_breakdown_body"></tbody>
            </table>
        </div>
        <div class="mt-1 text-muted small" id="day_summary"></div>
    </div>

    {{-- Leave Note --}}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('leave_reason', __('Leave Note'), ['class' => 'col-form-label']) }}<x-required></x-required>
                {{ Form::textarea('leave_reason', null, ['class' => 'form-control', 'required' => 'required', 'placeholder' => __('Leave Reason'), 'rows' => '3']) }}
            </div>
        </div>
    </div>

    {{-- Remark --}}
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('remark', __('Remark'), ['class' => 'col-form-label']) }}<x-required></x-required>
                @if ($plan->enable_chatgpt == 'on')
                    <a href="javascript:void(0)" data-size="md" class="btn btn-primary btn-icon btn-sm"
                        data-ajax-popup-over="true" id="grammarCheck"
                        data-url="{{ route('grammar', ['grammar']) }}" data-bs-placement="top"
                        data-title="{{ __('Grammar check with AI') }}">
                        <i class="ti ti-rotate"></i> <span>{{ __('Grammar check with AI') }}</span>
                    </a>
                @endif
                {{ Form::textarea('remark', null, ['class' => 'form-control grammer_textarea', 'required' => 'required', 'placeholder' => __('Leave Remark'), 'rows' => '3']) }}
            </div>
        </div>
    </div>

    @if (isset($setting['is_enabled']) && $setting['is_enabled'] == 'on')
        <div class="form-group col-md-6">
            {{ Form::label('synchronize_type', __('Synchroniz in Google Calendar ?'), ['class' => 'form-label']) }}
            <div class="form-switch">
                <input type="checkbox" class="form-check-input mt-2" name="synchronize_type"
                    id="switch-shadow" value="google_calender">
                <label class="form-check-label" for="switch-shadow"></label>
            </div>
        </div>
    @endif

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ __('Cancel') }}</button>
    <input type="submit" value="{{ __('Create') }}" class="btn btn-primary">
</div>
{{ Form::close() }}

<script>
(function () {
    'use strict';

    // Is the current user an employee? (employees cannot override status)
    var isEmployee = {{ \Auth::user()->type === 'employee' ? 'true' : 'false' }};

    // PHP date format → JS date format conversion (passed from server)
    var phpDateFormat = '{{ \App\Models\Utility::settings()['site_date_format'] ?? 'd-m-Y' }}';

    var dayNames = [
        '{{ __("Sun") }}','{{ __("Mon") }}','{{ __("Tue") }}',
        '{{ __("Wed") }}','{{ __("Thu") }}','{{ __("Fri") }}','{{ __("Sat") }}'
    ];

    // Map of leaveTypeId → {is_paid, remaining} populated by jsoncount AJAX
    var leaveTypeData = {};

    // ── Set today as default end date ──────────────────────────────────────
    $(document).ready(function () {
        var now = new Date();
        var mm  = String(now.getMonth() + 1).padStart(2, '0');
        var dd  = String(now.getDate()).padStart(2, '0');
        $('#end_date').val(now.getFullYear() + '-' + mm + '-' + dd);

        setTimeout(function () {
            var eid = $('#employee_id').val();
            if (eid) $('#employee_id').trigger('change');
        }, 100);
    });

    // ── Rebuild breakdown when dates change ───────────────────────────────
    $(document).on('change', '#start_date, #end_date', buildBreakdown);

    // ── Also rebuild when leave type changes (quota / pay type may differ) ─
    $(document).on('change', '#leave_type_id', function () {
        updateLeaveTypeInfo($(this).val());
        buildBreakdown();   // re-apply lock rules with new type info
    });

    // ── Load leave types with balance when employee changes ───────────────
    $(document).on('change', '#employee_id', function () {
        var employee_id = $(this).val();
        if (!employee_id) return;

        $.ajax({
            url: '{{ route('leave.jsoncount') }}',
            type: 'POST',
            data: { employee_id: employee_id, _token: '{{ csrf_token() }}' },
            success: function (data) {
                leaveTypeData = {};
                var oldval = $('#leave_type_id').val();

                $('#leave_type_id').empty();
                $('#leave_type_id').append('<option value="">{{ __("Select Leave Type") }}</option>');

                $.each(data, function (key, value) {
                    leaveTypeData[value.id] = {
                        is_paid:     value.is_paid ? 1 : 0,
                        remaining:   parseFloat(value.remaining),
                        days:        parseFloat(value.days),
                        total_leave: parseFloat(value.total_leave),
                    };

                    var label    = value.title + ' (' + value.total_leave + '/' + value.days
                                 + ' {{ __("used") }}, {{ __("Remaining") }}: ' + value.remaining + ')';
                    var disabled = (value.remaining <= 0 && value.is_paid) ? ' disabled' : '';

                    $('#leave_type_id').append(
                        '<option value="' + value.id + '"' + disabled
                        + ' data-is-paid="' + (value.is_paid ? 1 : 0) + '"'
                        + ' data-remaining="' + value.remaining + '">'
                        + label + '</option>'
                    );

                    if (oldval && oldval == value.id) {
                        $('#leave_type_id option[value="' + oldval + '"]').prop('selected', true);
                    }
                });

                updateLeaveTypeInfo($('#leave_type_id').val());
                buildBreakdown();
            }
        });
    });

    // ── Paid/unpaid badge + remaining info bar ─────────────────────────────
    // ── PHP → JS date formatter ────────────────────────────────────────────
    // Converts a JS Date object to the site's configured date format string
    function formatDate(dateObj) {
        var yyyy = dateObj.getFullYear();
        var mm   = String(dateObj.getMonth() + 1).padStart(2, '0');
        var dd   = String(dateObj.getDate()).padStart(2, '0');
        var m1   = String(dateObj.getMonth() + 1);   // no leading zero
        var d1   = String(dateObj.getDate());         // no leading zero

        // Map PHP tokens → actual values
        return phpDateFormat
            .replace('Y', yyyy)
            .replace('y', String(yyyy).slice(-2))
            .replace('m', mm)
            .replace('n', m1)
            .replace('d', dd)
            .replace('j', d1);
    }

    function updateLeaveTypeInfo(id) {
        if (!id) { $('#leave_type_info').hide(); return; }

        var d         = leaveTypeData[id];
        var opt       = $('#leave_type_id option[value="' + id + '"]');
        var isPaid    = d ? d.is_paid    : parseInt(opt.data('is-paid') || 1);
        var remaining = d ? d.remaining  : parseFloat(opt.data('remaining') || opt.data('days') || 0);

        var payBadge = isPaid
            ? '<span class="badge bg-success"><i class="ti ti-circle-check me-1"></i>{{ __("Paid Leave") }}</span>'
            : '<span class="badge bg-danger"><i class="ti ti-circle-x me-1"></i>{{ __("Unpaid Leave") }}</span>';

        var remClass = remaining > 0 ? 'text-success' : 'text-danger';
        var remText  = '<span class="' + remClass + ' fw-semibold">'
                     + '{{ __("Remaining") }}: ' + remaining + ' {{ __("day(s)") }}</span>';

        $('#leave_type_pay_badge').html(payBadge);
        $('#leave_type_remaining').html(remText);
        $('#leave_type_info').show();
    }

    // ── Build per-day breakdown table ──────────────────────────────────────
    function buildBreakdown() {
        var sd = $('#start_date').val();
        var ed = $('#end_date').val();

        if (!sd || !ed) { $('#day_breakdown_wrapper').hide(); return; }

        var start    = new Date(sd);
        var end      = new Date(ed);
        if (end < start) { $('#day_breakdown_wrapper').hide(); return; }

        var ltId      = $('#leave_type_id').val();
        var ltd       = ltId ? leaveTypeData[ltId] : null;
        var isPaid    = ltd ? ltd.is_paid   : 1;
        var remaining = ltd ? ltd.remaining : 0;

        var diffDays = Math.round((end - start) / 86400000) + 1;
        var tbody    = $('#day_breakdown_body');
        tbody.empty();

        // Track how many paid days we've "used up" while building rows
        var paidBudget = remaining;

        for (var i = 0; i < diffDays; i++) {
            var cur = new Date(start);
            cur.setDate(start.getDate() + i);

            var yyyy    = cur.getFullYear();
            var m       = String(cur.getMonth() + 1).padStart(2, '0');
            var d       = String(cur.getDate()).padStart(2, '0');
            var dateStr = yyyy + '-' + m + '-' + d;   // always Y-m-d for form keys
            var dateDisp = formatDate(cur);            // user's configured format for display
            var dayName = dayNames[cur.getDay()];

            // Determine status for this row:
            // • Leave type is unpaid          → always "unpaid", locked for employees
            // • Leave type is paid but quota exhausted → "unpaid", locked for employees
            // • Otherwise                     → "paid", editable
            var status, locked;

            if (!isPaid) {
                // Entire leave type is unpaid
                status = 'unpaid';
                locked = isEmployee;
            } else if (paidBudget <= 0) {
                // Quota exhausted for this row
                status = 'unpaid';
                locked = isEmployee;
            } else {
                status = 'paid';
                locked = false;
                paidBudget -= 1.0;  // reserve 1 day (full day assumption; half-day handled on change)
            }

            tbody.append(buildRow(dateStr, dateDisp, dayName, 'full_day', 'morning', status, locked));
        }

        updateSummary();
        $('#day_breakdown_wrapper').show();
    }

    // ── Build a single table row ───────────────────────────────────────────
    function buildRow(dateStr, dateDisp, dayName, duration, period, status, locked) {
        var periodStyle = duration === 'half_day' ? '' : 'display:none;';
        var uid         = dateStr.replace(/-/g, '_');
        var disAttr     = locked ? ' disabled' : '';
        var lockedBadge = locked
            ? '<span class="badge bg-secondary ms-1" title="{{ __("Auto-set based on leave type or quota") }}">'
              + '<i class="ti ti-lock"></i></span>'
            : '';

        // Hidden input to ensure the value is always submitted even when radios are disabled
        var hiddenStatus = locked
            ? '<input type="hidden" name="day_status[' + dateStr + ']" value="' + status + '">'
            : '';

        return ''
            + '<tr data-date="' + dateStr + '">'
            + '<td><small>' + dateDisp + '</small></td>'
            + '<td><small>' + dayName + '</small></td>'

            // Duration
            + '<td>'
            +   '<div class="form-check form-check-inline">'
            +     '<input class="form-check-input dur-radio" type="radio"'
            +       ' name="day_duration[' + dateStr + ']"'
            +       ' id="full_' + uid + '" value="full_day"'
            +       (duration !== 'half_day' ? ' checked' : '') + '>'
            +     '<label class="form-check-label" for="full_' + uid + '">{{ __("Full") }}</label>'
            +   '</div>'
            +   '<div class="form-check form-check-inline">'
            +     '<input class="form-check-input dur-radio" type="radio"'
            +       ' name="day_duration[' + dateStr + ']"'
            +       ' id="half_' + uid + '" value="half_day"'
            +       (duration === 'half_day' ? ' checked' : '') + '>'
            +     '<label class="form-check-label" for="half_' + uid + '">{{ __("Half") }}</label>'
            +   '</div>'
            + '</td>'

            // Period
            + '<td class="period-cell" style="' + periodStyle + '">'
            +   '<select name="half_day_period_day[' + dateStr + ']" class="form-control form-control-sm period-select"' + disAttr + '>'
            +     '<option value="morning"   ' + (period === 'morning'   ? 'selected' : '') + '>{{ __("Morning") }}</option>'
            +     '<option value="afternoon" ' + (period === 'afternoon' ? 'selected' : '') + '>{{ __("Afternoon") }}</option>'
            +   '</select>'
            + '</td>'

            // Status — locked rows show badge + hidden input; editable rows show radios
            + '<td>'
            +   hiddenStatus
            +   '<div class="form-check form-check-inline">'
            +     '<input class="form-check-input stat-radio" type="radio"'
            +       ' name="' + (locked ? '_day_status_display[' + dateStr + ']' : 'day_status[' + dateStr + ']') + '"'
            +       ' id="paid_' + uid + '" value="paid"'
            +       (status === 'paid'   ? ' checked' : '')
            +       disAttr + '>'
            +     '<label class="form-check-label text-success" for="paid_' + uid + '">{{ __("Paid") }}</label>'
            +   '</div>'
            +   '<div class="form-check form-check-inline">'
            +     '<input class="form-check-input stat-radio" type="radio"'
            +       ' name="' + (locked ? '_day_status_display[' + dateStr + ']' : 'day_status[' + dateStr + ']') + '"'
            +       ' id="unpaid_' + uid + '" value="unpaid"'
            +       (status === 'unpaid' ? ' checked' : '')
            +       disAttr + '>'
            +     '<label class="form-check-label text-danger" for="unpaid_' + uid + '">{{ __("Unpaid") }}</label>'
            +   '</div>'
            +   lockedBadge
            + '</td>'

            + '</tr>';
    }

    // ── Duration change: toggle period cell + rebalance quota locks ────────
    $(document).on('change', '.dur-radio', function () {
        var row  = $(this).closest('tr');
        var cell = row.find('.period-cell');
        cell[$(this).val() === 'half_day' ? 'show' : 'hide']();
        updateSummary();
        // Note: quota re-balancing on half/full toggle is complex;
        // full rebuild is the cleanest approach when employee changes duration
        if (!isEmployee) updateSummary();
    });

    $(document).on('change', '.stat-radio', updateSummary);

    // ── Live summary ───────────────────────────────────────────────────────
    function updateSummary() {
        var total = 0, paid = 0, unpaid = 0;

        $('#day_breakdown_body tr').each(function () {
            var durVal;
            var checkedDur = $(this).find('.dur-radio:checked');
            durVal = checkedDur.length ? checkedDur.val() : 'full_day';

            // Read status from hidden input (locked) or checked radio (editable)
            var statVal;
            var hiddenStat = $(this).find('input[type="hidden"][name^="day_status"]');
            if (hiddenStat.length) {
                statVal = hiddenStat.val();
            } else {
                var checkedStat = $(this).find('.stat-radio:checked');
                statVal = checkedStat.length ? checkedStat.val() : 'paid';
            }

            var days = durVal === 'half_day' ? 0.5 : 1.0;
            total += days;
            if (statVal === 'paid') paid += days; else unpaid += days;
        });

        $('#day_summary').html(
            '<strong>{{ __("Total") }}:</strong> '  + total  + ' &nbsp;|&nbsp; '
          + '<span class="text-success"><strong>{{ __("Paid") }}:</strong> '   + paid   + '</span> &nbsp;|&nbsp; '
          + '<span class="text-danger"><strong>{{ __("Unpaid") }}:</strong> '  + unpaid + '</span>'
        );
    }

}());
</script>
